# netlify.toml for Vite + React + TypeScript

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# SPA fallback routing (e.g. /login, /dashboard)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Netlify Dev settings
[dev]
  command = "npm run dev" # or "vite"
  port = 5173
  publish = "dist"
