name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for SonarCloud to properly analyze the code

    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18


      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests with coverage
        working-directory: server
        run: |
          npm run test -- --coverage
          mkdir -p coverage
          [ -f coverage/lcov.info ] || echo "No coverage file generated" > coverage/lcov.info


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_cou-visionary-coders
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.projectName="cou-visionary-coders"
            -Dsonar.sources=server/src
            -Dsonar.javascript.lcov.reportPaths=server/coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=server/coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/dist/**
            -Dsonar.ci.enabled=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PORT: "3000"
          DATABASE_URL: mongodb+srv://Cou-Visionary-Coder:vtE4OlRE84vFJXfk@cluster0.dwtnipt.mongodb.net/Cou-Visionary-Coder?retryWrites=true&w=majority&appName=Cluster0
          JWT_SECRET_KEY: 8189cfc94fd7574790ec341d42cff48b3e26eaeb289349f17c1527254be5a67bd244de0ce8e597a0f32c023c166ada925110e0f58c8a77f8256d945f5696982a  # This is a secret key, you can generate your own using any online tool
          NODE_ENV: development
          SESSION_SECRET: shuvo
