name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for SonarCloud to properly analyze the code

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      # Step 4: Run frontend tests with coverage
      - name: Run frontend tests with coverage
        working-directory: client
        run: |
          npm run test -- --coverage
          mkdir -p coverage
          [ -f coverage/lcov.info ] || echo "No coverage file generated" > coverage/lcov.info


      # Step 5: Install backend dependencies
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      # Step 6: Run backend tests with coverage
      - name: Run backend tests with coverage
        working-directory: server
        run: |
          npm run test -- --coverage
          mkdir -p coverage
          [ -f coverage/lcov.info ] || echo "No coverage file generated" > coverage/lcov.info


      # Step 7: SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_cou-visionary-coders
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.projectName="cou-visionary-coders"
            -Dsonar.sources=client/src,server/src
            -Dsonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
            -Dsonar.coverage.exclusions=**/test/**,**/mock/**
            -Dsonar.ci.enabled=true
            -Dsonar.analysis.automatic=false
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          VITE_FIREBASE_API_KEY: "AIzaSyC5G67obM_4iiF_Am28z5ifbTEbzmDe9Xc"
          VITE_FIREBASE_AUTH_DOMAIN: "cou-visionary-coders.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "cou-visionary-coders"
          VITE_FIREBASE_STORAGE_BUCKET: "cou-visionary-coders.firebasestorage.app"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "430900147490"
          VITE_FIREBASE_APP_ID: "1:430900147490:web:d52584eea91ab5d752e17b"
          VITE_FIREBASE_MEASUREMENT_ID: "G-GKGQBD8VVX"
          VITE_BACKEND_BASE_URL: "https://halal-bondhon.vercel.app"
          PORT: "3000"
          DATABASE_URL: mongodb+srv://Cou-Visionary-Coder:vtE4OlRE84vFJXfk@cluster0.dwtnipt.mongodb.net/Cou-Visionary-Coder?retryWrites=true&w=majority&appName=Cluster0
          JWT_SECRET_KEY: 8189cfc94fd7574790ec341d42cff48b3e26eaeb289349f17c1527254be5a67bd244de0ce8e597a0f32c023c166ada925110e0f58c8a77f8256d945f5696982a  # This is a secret key, you can generate your own using any online tool
          NODE_ENV: development
          SESSION_SECRET: shuvo
