name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for SonarCloud to properly analyze the code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      - name: Run frontend tests with coverage
        working-directory: client
        run: |
          npm run coverage
          # Ensure coverage files are in the expected location
          mkdir -p coverage
          [ -f coverage/lcov.info ] || echo "No coverage file generated" > coverage/lcov.info

      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_cou-visionary-coders
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.projectName="cou-visionary-coders"
            -Dsonar.sources=client/src,server/src
            -Dsonar.javascript.lcov.reportPaths=client/coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=client/coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
            -Dsonar.coverage.exclusions=**/test/**,**/mock/**
            -Dsonar.ci.enabled=true
            -Dsonar.analysis.automatic=false
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
